# data_visualization

## Imports and configs

### Fonts setup

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

fm.findSystemFonts(fontpaths=["/usr/share/fonts/truetype/"])

plt.rcParams["font.family"] = "Times New Roman"

plt.text(0.5, 0.5, 'Teste com Times New Roman', fontsize=12, ha='center')
plt.show()

### Imports

In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.manifold import MDS
from skbio.diversity import alpha_diversity
from scipy.spatial.distance import pdist, squareform
from skbio.diversity import beta_diversity

## Data Preparation and Wrangling

In [4]:
target_dir = os.path.expanduser('~/git/sci_init/04_bioreactor_ml_project/data_viz/')
os.chdir(target_dir)
os.getcwd()

'/home/guilherme/git/sci_init/04_bioreactor_ml_project/data_viz'

In [11]:
meta_all = pd.read_csv("../data/metadata/02_metadata_enrichment_clean.csv", index_col="Cluster sample ID")
meta_all.head()

,Metagenomic samples,Cluster sample ID (Larvae/QC_output ),Unnamed: 2,Unnamed: 4,Unnamed: 5,EXPERIMENT,TRANSFER,Gut Compartment,Replicate,Sampling day,...,Acetic_acid_mg/L,Propionic_acid_mg/L,Butyric_acid_mg/L,Cumulative CH4 _mL,Cumulative_CH4 _mL/gVS,H2_%,CO2_%,O2_%,N2_%,CH4_%
Cluster sample ID,,,,,,,,,,,,,,,,,,,,,
UNDR03_2,2,UNDR03_2_1.fastq.tar.gz,UNDR03_2_2.fastq.tar.gz,1st_1T_midA,136,1,1T,Midgut,A,30,...,"4169,61","283,48","140,39","0,61","1,36","0,25","44,05","0,00","50,97","4,73"
UNDR03_3,3,UNDR03_3_1.fastq.tar.gz,UNDR03_3_2.fastq.tar.gz,1st_1T_midB,137,1,1T,Midgut,B,30,...,"4518,43","307,68","80,14","0,80","1,77","0,30","44,22","0,00","50,27","5,21"
UNDR03_4,4,UNDR03_4_1.fastq.tar.gz,UNDR03_4_2.fastq.tar.gz,1st_1T_midC,138,1,1T,Midgut,C,30,...,"4857,67","365,90","110,54","0,18","0,41","0,64","49,82","0,00","48,51","1,03"
UNDR03_5,5,UNDR03_5_1.fastq.tar.gz,UNDR03_5_2.fastq.tar.gz,1st_1T_hidA,139,1,1T,Hindgut,A,30,...,"4133,13","413,10","77,77","3,24","7,20","0,20","47,04","0,00","39,14","13,62"
UNDR03_6,6,UNDR03_6_1.fastq.tar.gz,UNDR03_6_2.fastq.tar.gz,1st_1T_hidB,140,1,1T,Hindgut,B,30,...,"4116,09","379,55","74,02","3,99","8,85","0,00","47,55","0,00","37,30","15,15"

In [12]:
from sklearn.preprocessing import FunctionTransformer
from skbio.stats.composition import multi_replace
from optuna.trial import Trial, FixedTrial
from pandas import DataFrame
def clr_transform(X: np.ndarray | DataFrame) -> np.ndarray | DataFrame:
    """
    Implements the Centered Log Ratio transform, which is recommended for
    dealing with compositional data as such generated by High Throughput
    Sequencing
    """
    # Need to make sure X is at least 2d to not have problems with LeaveOneOut
    X_zeroless = multi_replace(np.asarray(X))
    X_2d = np.atleast_2d(X_zeroless)

    log_X = np.log(X_2d)
    geo_mean = log_X.mean(axis=1, keepdims=True)

    return log_X - geo_mean


class CLRTransformer:
    def create_scaler(self, trial: Trial | FixedTrial):
        return FunctionTransformer(clr_transform, feature_names_out='one-to-one')
asv_all = pd.read_csv("../../04_bioreactor_ml_project/data/genomic/03_map_complete_absolute_n_hits_table.csv", index_col=0).T
asv_all = CLRTransformer().create_scaler(None).set_output(transform="pandas").fit_transform(asv_all)
asv_all

,UNDR01_2HCb-bin.0,UNDR01_2HCb-bin.13,UNDR01_2HCb-bin.15,UNDR01_2HCb-bin.18,UNDR01_2HCb-bin.19,UNDR01_2HCb-bin.21,UNDR01_2HCb-bin.22,UNDR01_2HCb-bin.44,UNDR01_2HCb-bin.49,UNDR01_2HCb-bin.5,...,merge_NG-28520_B96-bin.22,merge_NG-28520_B96-bin.28,merge_NG-28520_B96-bin.29,merge_NG-28520_B96-bin.32,merge_NG-28520_B96-bin.47,merge_NG-28520_B96-bin.48,merge_NG-28520_B96-bin.49,merge_NG-28520_B96-bin.72,merge_NG-28520_B96-bin.8,merge_NG-28520_B96-bin.82
UNDR01_2HCb,5.390542,3.268799,3.924842,4.164478,2.948034,7.259905,3.408711,3.152678,7.525066,4.164121,...,-2.677248,-4.443689,-4.107217,0.742858,-3.507596,-2.635400,2.659674,0.321898,-1.249106,-3.942914
UNDR01_2MCb,4.656991,0.236491,1.300645,1.574035,0.401868,4.408219,0.216123,2.051893,8.294190,1.398128,...,-1.660629,-3.420640,-4.178326,1.530997,-2.792032,-1.756477,3.186812,0.719016,-0.991973,-4.583791
UNDR03_102,-4.126304,-6.118734,-3.012654,-4.578289,-6.118734,-0.844027,-3.783359,-5.271436,-0.591954,-5.831052,...,-0.259849,0.551609,-0.361938,-4.221614,0.923260,1.796614,-0.961597,-2.446662,-2.798506,3.225408
UNDR03_117,-2.462026,-6.666719,-1.661181,-3.894130,-6.666719,-1.554731,-3.055801,-4.181812,-0.326360,-5.973572,...,-3.111371,1.343309,0.472148,-4.101770,1.010218,0.732679,-1.896034,-2.492332,-2.623668,1.604574
UNDR03_118,-2.478680,-6.089598,-6.089598,-2.911544,-6.089598,-1.758864,-3.838306,-6.089598,-0.230237,-4.990985,...,-2.998555,1.278742,0.527137,-5.684133,1.048078,0.806085,-1.658781,-2.426036,-2.705207,2.751417
UNDR03_119,-2.843943,-5.616532,-5.616532,-4.923385,-4.923385,-1.556089,-3.824772,-4.517920,-0.599252,-1.869726,...,-1.538994,0.877222,0.372430,-2.672093,0.954351,0.633443,-2.572009,-2.284327,-2.977475,2.451871
UNDR03_121,-2.906704,-1.784195,-6.690893,-3.746454,-5.997746,-1.628298,-3.746454,-3.800522,-0.304014,-5.997746,...,-0.347013,3.190297,0.601444,-4.493669,0.625655,1.706615,-1.059682,-2.516506,2.256262,3.700683
UNDR03_122,-3.412730,-1.745464,-1.745464,-3.688984,-6.780026,-1.711122,-3.735504,-4.071976,-0.742155,-6.086879,...,0.171746,3.365584,0.883851,-4.477441,0.910717,1.699257,-0.079295,-2.258238,2.953859,1.467980
UNDR03_123,-3.099181,-6.069595,-6.069595,-4.123685,-5.376448,-1.792929,-4.123685,-4.816833,-0.729656,-5.376448,...,0.259234,2.964902,0.737234,-4.683301,0.682675,1.525540,-0.164234,-2.573088,2.819989,2.626664
UNDR03_1HAb,5.880708,2.154382,1.618177,3.224087,-1.086358,0.423550,3.607160,0.608774,3.869654,-0.596810,...,-4.030797,-1.833429,-2.239038,-0.258036,-2.932185,-3.337650,-3.625332,-0.269597,-3.625332,-2.932185
UNDR03_1HBb,5.966696,2.428872,2.025769,3.397570,-0.689695,0.648971,3.618823,0.430390,4.175977,-0.469346,...,-4.450895,-6.060333,-2.276144,-0.579694,-3.662438,-3.662438,-3.115894,0.187710,-2.189132,-3.064601
UNDR03_1MAa,1.650707,-1.455915,-0.565409,-0.345255,-1.455915,1.743870,-0.930649,-3.853811,8.297738,-3.266024,...,-4.770101,-4.770101,-3.517338,3.145794,-1.512005,-3.671489,-1.243741,3.107106,0.320577,-5.463249
UNDR03_1MCa,1.903413,-1.152799,-0.577435,-0.279390,-1.243183,1.736200,-0.577435,-5.547248,8.634619,-2.908191,...,-3.601338,-3.601338,-3.467806,3.144739,-2.081512,-3.937810,-1.763058,3.377675,-0.033819,-1.033083
UNDR03_2,2.575498,-4.415909,0.324666,-5.109056,-3.856293,2.559739,-3.499618,-3.237254,2.305818,-5.109056,...,-1.069649,-0.631719,-1.101723,-3.722762,-0.381668,-1.248326,-1.069649,-1.120072,-5.109056,-1.101723
UNDR03_22,3.434195,-1.607436,0.007542,-2.055461,-5.190955,3.759059,-1.823659,-3.804661,2.014680,-1.477383,...,-0.258608,0.526073,0.198117,-4.092343,0.706199,-0.481425,-0.258608,-1.201971,-3.804661,-0.249313
UNDR03_23,4.582910,-3.997321,0.074551,-1.837836,-3.709639,4.597266,-1.599425,-2.611026,1.534750,-4.402786,...,-0.164083,-1.358263,0.621095,-3.709639,1.638659,-0.574144,-4.402786,-0.665116,-4.402786,-0.259651
UNDR03_24,4.428387,-3.549787,0.618428,-1.398024,-5.159225,5.288707,-1.521638,-1.758027,2.008585,-2.761329,...,-5.159225,-0.574257,0.187883,-2.674318,2.209115,-0.789777,0.103601,-0.253950,-3.549787,-0.388540
UNDR03_25,2.990571,-2.100619,-1.695154,-2.143179,-3.486914,2.289189,-2.020577,-3.486914,1.795444,-5.278673,...,-2.282941,-0.015983,-0.329913,-5.278673,1.654750,-1.119790,-0.400268,-1.667755,-4.180061,-0.974608
UNDR03_26,4.374350,-1.608525,0.395796,-0.847555,-2.013990,3.202089,-0.442090,-2.284281,1.650920,-3.166670,...,-5.651577,-0.318858,2.445545,-2.432701,1.286708,-1.320843,-4.265282,-0.563980,-3.166670,-3.454352
UNDR03_27,5.084958,-1.736741,-3.152023,0.677896,-1.380066,4.026073,-0.322276,-4.886624,2.166673,-3.212648,...,-4.886624,0.069203,2.168976,-2.807183,2.321482,-3.346179,-3.587341,-0.274810,-3.500330,-3.277186
UNDR03_2HBb,4.774581,2.570808,3.713563,3.555585,2.931144,7.106692,2.430664,2.299957,6.828615,3.847259,...,-2.183580,-4.399496,-3.442535,0.752922,-2.679429,-2.383336,2.282920,0.279310,-1.134890,-3.479439
UNDR03_2MAa,4.846517,0.552977,1.223384,1.264568,0.575573,3.820415,0.487086,2.707787,7.665944,1.686838,...,-3.591633,-3.193950,-3.856325,1.480630,-3.178446,-2.573709,3.017246,0.565068,-1.270614,-4.867926
UNDR03_2MBb,4.348038,0.075960,0.910426,1.597300,-0.023717,4.388413,-0.137915,1.336224,8.478941,0.749593,...,-1.851844,-3.521001,-4.881977,2.073615,-2.317028,-1.589851,3.522943,1.257476,-0.313471,-5.105121
UNDR03_3,2.895706,-5.173324,0.069745,-3.227414,-5.866471,3.059582,-3.615179,-4.362393,2.408269,-4.613708,...,-6.559618,-0.373409,-0.466048,-2.647595,1.055680,0.098393,-0.958600,-0.928406,-4.767859,-0.543461
UNDR03_4,2.527690,-5.346098,0.087624,-2.903751,-6.039245,2.494805,-4.093335,-3.266656,2.173052,-5.346098,...,-0.978919,-1.819737,-0.408033,-2.455726,-0.390271,0.140772,-0.978919,-0.976650,-6.039245,-0.455749
UNDR03_5,3.110237,-0.993532,0.950502,-2.282775,-3.797902,3.140754,-0.449168,-2.929402,0.609833,-3.359647,...,-2.929402,-2.471711,-2.449829,-3.561513,-0.056272,-1.272173,-5.119658,-1.413737,-4.131046,-2.146043
UNDR03_6,2.870851,-1.027320,0.941382,-2.772560,-3.917692,3.257142,-0.565285,-2.867870,0.414294,-3.351297,...,-6.962215,-2.605506,-0.693118,-4.189626,0.174269,-0.127030,-6.269067,-2.158193,-4.323157,-4.017776
UNDR03_7,2.851385,-1.115360,0.373560,-3.187701,-4.324779,2.291207,-0.685646,-2.840504,0.367647,-3.825788,...,-2.015557,-1.421420,-0.111345,-4.267621,-0.875726,-0.961548,-2.015557,-2.485164,-4.673086,-5.366233
UNDR03_74,-0.531617,-5.613022,0.201855,-4.473587,-4.226727,2.068654,-4.514409,-2.904971,-0.210344,-5.495239,...,-3.649412,-2.681828,-1.485887,-5.294568,-0.157701,0.929810,-1.204779,-3.057734,-3.285744,3.161813
UNDR03_75,-0.126201,-5.925293,0.352853,-5.136836,-4.202527,2.769175,-4.490209,-2.544299,-0.005325,-5.232146,...,-4.167436,-2.381440,-1.020019,-5.232146,-0.172721,1.545956,-0.628978,-2.991437,-2.861903,0.266251
UNDR03_76,-0.331681,-5.570779,0.264032,-5.388457,-4.318016,2.707929,-4.695310,-2.842926,-0.301375,-5.308415,...,-3.981544,-2.448414,-1.393319,-5.165314,0.096685,1.060828,-1.207680,-3.094240,-3.319487,2.163343
UNDR03_78,1.287391,-1.739415,-0.718430,-5.104153,-0.426490,3.440453,-2.376543,-0.863093,-0.739876,-2.530693,...,-4.272856,-0.529061,-1.157192,-5.404258,-0.784199,-0.672896,-1.411577,-3.451230,-2.459819,1.068938
UNDR03_79,1.455304,-1.679718,-0.947738,-4.928540,-0.212187,3.596502,-2.199381,-0.627182,-0.623395,-3.327135,...,-3.752967,-0.672077,-0.990460,-5.662510,-0.684053,0.731499,-1.428403,-3.335232,-1.975716,-0.678903
UNDR03_80,1.150289,-1.876935,-1.260050,-5.453486,-0.394854,3.813914,-2.635087,-0.842706,-0.692916,-3.374044,...,-4.488405,-0.386155,-1.213059,-5.281635,-1.255344,0.032348,-1.169899,-3.693475,-2.512342,1.417670
merge_NG-28520_B06,-2.921649,-3.158037,-5.172941,-2.432100,-4.479793,-1.738953,-3.786646,-3.668863,-0.587973,-3.668863,...,-4.074328,-0.790914,1.054584,-2.339727,1.413231,0.299330,-1.575628,2.867990,-2.464890,4.779051
merge_NG-28520_B11,-4.827830,-3.847001,-5.233296,-2.930710,-4.134683,-2.119780,-3.287385,-4.134683,-0.820497,-3.528547,...,-4.134683,0.641635,1.392097,-2.559147,1.380089,0.270001,-2.119780,0.482086,-1.556995,5.496350
merge_NG-28520_B16,-5.257195,-4.340905,-1.737332,-2.814848,-4.851730,-1.791460,-3.005904,-4.340905,-0.838355,-5.257195,...,-3.753118,-0.098140,1.478585,-2.394995,1.736279,0.231742,-1.659883,0.969341,-0.007543,5.176391
merge_NG-28520_B22,-3.454625,-4.466226,-4.243083,-2.674467,-4.753908,-1.920695,-2.807998,-3.906610,-0.616079,-4.243083,...,-4.060761,1.280775,1.639682,-2.761478,1.706518,0.269972,-1.458071,1.892915,1.027864,4.875252
merge_NG-28520_B28,-3.936955,-3.300966,-6.134179,-2.607819,-4.342420,-1.346687,-2.766883,-5.035567,-0.256443,-4.342420,...,-3.569230,0.882431,5.606599,-2.637672,1.851305,-0.394386,-0.876684,-0.492272,0.754393,4.114032
merge_NG-28520_B34,-3.111017,-3.191060,-5.675966,-3.191060,-4.982819,-1.413286,-2.343762,-3.730056,-0.123007,-3.373381,...,-3.884207,0.086085,1.522217,1.544407,1.622479,-0.264320,-1.744141,6.357228,-2.012405,3.174981
merge_NG-28520_B39,-4.432529,-4.027063,-1.789492,-3.451699,-5.531141,-1.817569,-2.727780,-4.144846,-0.611160,-4.144846,...,1.291057,0.787827,1.543399,-0.930983,1.741258,0.052355,-2.535409,5.954578,-2.586702,4.364340
merge_NG-28520_B44,-4.442004,-3.594706,-1.895888,-3.189241,-4.624326,-1.985268,-2.496094,-3.835868,-0.778442,-4.624326,...,2.483264,-0.023163,1.664648,2.306169,1.831816,0.087005,-2.737256,4.279299,-0.500422,4.162376
merge_NG-28520_B50,-5.191966,-3.805672,-1.994841,-2.451126,-3.582529,-1.407777,-2.627017,-3.687889,-0.632840,-3.246056,...,0.935994,0.546217,7.559590,0.444607,1.321264,-0.464579,-2.196234,4.143684,1.173644,4.095381
merge_NG-28520_B56,-4.536930,-4.026105,-6.328690,-2.745171,-4.536930,-1.693961,-3.150636,-4.536930,-0.456572,-4.249248,...,1.059019,1.202326,5.901241,1.491750,1.742216,-0.084523,-0.764170,3.129291,0.813347,3.921998
merge_NG-28520_B62,-3.791472,-4.379259,-5.988697,-3.155483,-4.602402,-1.877823,-3.423747,-4.484619,-0.641589,-5.583232,...,3.991451,2.859956,0.290762,-0.864733,0.547995,2.170535,2.595688,4.499225,3.217937,4.503383
merge_NG-28520_B67,-4.984200,-4.028688,-6.593637,-3.760424,-4.984200,-2.139290,-3.458143,-5.207343,-0.941148,-5.207343,...,2.706452,2.544347,0.801470,2.631394,2.518649,0.755593,2.847735,5.499031,3.468604,4.272203
merge_NG-28520_B72,-5.043893,-4.484277,-6.430187,-3.294693,-4.820749,-2.335842,-3.539815,-4.232962,-0.983449,-5.043893,...,3.047352,2.563613,0.961228,2.145275,2.425334,0.226540,2.421620,4.647453,2.971600,4.322276
merge_NG-28520_B78,-4.489598,-3.735826,-6.569040,-3.013691,-4.959602,-1.915079,-3.236835,-5.182745,-0.996885,-4.777280,...,2.527460,2.591165,5.619439,1.680274,2.185279,0.130461,2.333824,4.129836,2.677440,4.189161
merge_NG-28520_B84,-4.762163,-4.069016,-5.678454,-3.280559,-4.292160,-1.940784,-3.004305,-4.762163,-0.854148,-5.272989,...,2.316853,2.557966,5.210374,0.703362,2.068927,0.276087,1.553556,2.464773,3.193753,4.310844
merge_NG-28520_B85,-2.113765,-5.189540,-1.616701,-2.732805,-4.090928,-1.663180,-3.343714,-3.890257,-0.498192,-5.595005,...,-4.678715,2.400638,0.128580,-2.574581,-0.042046,0.540559,-0.306738,-2.025473,-0.880981,4.268649
merge_NG-28520_B88,-1.917836,-3.635488,-6.274545,-2.942340,-4.482786,-1.649572,-3.230023,-4.077320,-0.580813,-5.175933,...,-4.195103,2.336139,-0.074036,-2.115662,0.033553,0.620125,-0.525152,-1.984086,-0.854010,4.339438
merge_NG-28520_B91,-3.021441,-4.002270,-5.506348,-2.941398,-3.896910,-1.909035,-3.366282,-4.407735,-0.735663,-4.813201,...,3.153126,3.181432,0.017111,-2.733759,0.192422,2.059963,3.239653,-2.307675,2.982446,5.039323
merge_NG-28520_B94,-3.337701,-4.293212,-5.902650,-2.958211,-5.209503,-2.074009,-2.958211,-5.902650,-0.840055,-5.209503,...,-2.724596,3.589782,3.717877,-1.668544,0.613543,1.107662,1.812027,0.592615,3.592568,2.679581
merge_NG-28520_B95,-1.858817,-4.488906,-6.568347,-3.167150,-4.776588,-1.230809,-3.572615,-5.469735,0.850434,-5.182053,...,4.503170,2.449015,3.627474,5.441303,1.022000,0.692878,0.513361,7.758329,0.584704,3.558404
merge_NG-28520_B96,-3.509128,-4.202275,-2.166263,-4.202275,-5.049573,-2.087742,-3.375597,-4.068744,-0.994894,-4.068744,...,3.946584,4.192105,4.705724,4.579522,5.339074,3.199566,4.255532,5.665030,4.034864,3.429503

In [13]:
merged = pd.merge(meta_all[['Gut Compartment', 'EXPERIMENT', 'TRANSFER']], asv_all,
                  how='inner', left_index=True, right_index=True)
merged.info()

<class 'pandas.DataFrame'>
Index: 24 entries, UNDR03_2 to UNDR03_123
Columns: 592 entries, Gut Compartment to merge_NG-28520_B96-bin.82
dtypes: float64(589), int64(1), str(2)
memory usage: 111.6 KB

In [14]:
meta_all.index

Index(['UNDR03_2', 'UNDR03_3', 'UNDR03_4', 'UNDR03_5', 'UNDR03_6', 'UNDR03_7',
       'UNDR03_22', 'UNDR03_23', 'UNDR03_24', 'UNDR03_25', 'UNDR03_26',
       'UNDR03_27', 'UNDR03_74', 'UNDR03_75', 'UNDR03_76', 'UNDR03_78',
       'UNDR03_79', 'UNDR03_80', 'UNDR03_117', 'UNDR03_118', 'UNDR03_119',
       'UNDR03_121', 'UNDR03_122', 'UNDR03_123'],
      dtype='str', name='Cluster sample ID')

In [18]:
def update_categoria(row):
    return f"{row['TRANSFER']}-{row['EXPERIMENT']}"
meta_all["TRANSFER"] = meta_all.apply(update_categoria, axis=1)
meta_all["TRANSFER"].unique()

<ArrowStringArray>
['1T-1', '3T-1', '1T-2', '3T-2']
Length: 4, dtype: str

## Visual Analysis

### Relevant imports

In [25]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.manifold import MDS
from skbio.diversity import alpha_diversity
from skbio.stats.distance import permanova
from scipy.spatial.distance import squareform
from scipy.spatial import distance_matrix
from scipy.stats import ttest_ind
from skbio import DistanceMatrix
from scipy.stats import kruskal

In [21]:
metadata = meta_all.loc[:, ['Gut Compartment', 'EXPERIMENT', 'TRANSFER']].copy()
metadata.shape

(24, 3)

### Markers for Plots

In [38]:
px_markers = {
    '3T-1': 2,         # diamond
    '3T-2': 302,       # open diamond
    '1T-1': 0,         # círculo
    '1T-2': 300          # circulo aberto com ponto
}

### Distance

In [35]:
asv_all = asv_all.loc[meta_all.index]
dist_matrix = pdist(asv_all)
dist_matrix_square = squareform(dist_matrix)
print(dist_matrix.shape)
print(dist_matrix_square.shape)

(276,)
(24, 24)

### NMDS

In [41]:
order = ['1T-1', '1T-2','3T-1', '3T-2']
mds = MDS(n_components=2, metric='precomputed', random_state=42,
          metric_mds=True, n_init=4, init='random')
nmds_results = mds.fit_transform(dist_matrix_square)

metadata['NMDS1'] = nmds_results[:, 0]
metadata['NMDS2'] = nmds_results[:, 1]
import plotly.express as px
fig = px.scatter(metadata, x='NMDS1', y='NMDS2', color='Gut Compartment',
                symbol='TRANSFER', category_orders={'Gut Compartment': ['Midgut', 'Hindgut'],
                                                    'Category': order},
                symbol_map=px_markers, title='nMDS of Microbial Distribution')
fig.update_traces(marker={'size':14})
fig.update_layout(width=1200, height=700)
y_range = [metadata['NMDS2'].min()-0.1, metadata['NMDS2'].max()+0.1]
x_range = [metadata['NMDS1'].min()-0.1, metadata['NMDS1'].max()+0.1]
fig.update_yaxes(range=y_range)
fig.update_xaxes(range=x_range)
for point in fig.data:
    group = point.legendgroup.split(',')[0]
    point.legendgroup = group
    point.legendgrouptitle.text = group
    count = len(point.x)
    point.name = point.name.split(',')[1].strip() + f' (n = {count})'
fig.update_layout(legend_groupclick="toggleitem")

show_all = [True] * len(fig.data)
hide_all = ['legendonly'] * len(fig.data)
midgut_only = [True if trace.legendgroup == 'Midgut' else 'legendonly' for trace in fig.data]
hindgut_only = [True if trace.legendgroup == 'Hindgut' else 'legendonly' for trace in fig.data]

fig.update_layout(
    title_pad_l=300,
    updatemenus=[
        dict(
            type='buttons',
            direction='left',
            xanchor='left',
            x=1.0, # Adjust X and Y to position the buttons where you like
            y=1.16,
            showactive=False,
            buttons=[
                dict(label='Show All', method='restyle', args=['visible', show_all]),
                dict(label='Hide All', method='restyle', args=['visible', hide_all]),
            ]
        ),
        dict(
            type='buttons',
            direction='left',
            xanchor='left',
            x=1.0, # Adjust X and Y to position the buttons where you like
            y=1.1,
            showactive=False,
            buttons=[
                dict(label='Midgut Only', method='restyle', args=['visible', midgut_only]),
                dict(label='Hindgut Only', method='restyle', args=['visible', hindgut_only]),
            ]
        )
    ]
)
fig.show()
fig.write_html('nmds_gut_cat_interactive.html')

### PCA

In [47]:
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 1. Prepare your data
# Note: Replace 'feature_matrix' with your actual sample-by-feature abundance dataframe.
# Standardizing the features is highly recommended for PCA.

# 2. Run PCA
pca = PCA(n_components=2, random_state=42)
pca_results = pca.fit_transform(asv_all)

# Extract explained variance to make your axis labels highly informative
exp_var = pca.explained_variance_ratio_ * 100

# Add PCA results to your metadata dataframe
metadata['PC1'] = pca_results[:, 0]
metadata['PC2'] = pca_results[:, 1]

# 3. Plotting with Plotly Express
order = ['1T-1', '1T-2', '3T-1', '3T-2']

fig = px.scatter(
    metadata, 
    x='PC1', 
    y='PC2', 
    color='Gut Compartment',
    symbol='TRANSFER', 
    category_orders={'Gut Compartment': ['Midgut', 'Hindgut'], 'Category': order},
    symbol_map=px_markers, 
    title='PCA of CLR-Transformed Microbial Distribution',
    labels={'PC1': f'PC1 ({exp_var[0]:.1f}%)', 'PC2': f'PC2 ({exp_var[1]:.1f}%)'}
)

# 4. Styling and Layout Customization (Preserving your exact setup)
fig.update_traces(marker={'size':14})
fig.update_layout(width=1200, height=700)

y_range = [metadata['PC2'].min() - 0.1, metadata['PC2'].max() + 0.1]
x_range = [metadata['PC1'].min() - 0.1, metadata['PC1'].max() + 0.1]
fig.update_yaxes(range=y_range)
fig.update_xaxes(range=x_range)

# Clean up legend groups and names
for point in fig.data:
    group = point.legendgroup.split(',')[0]
    point.legendgroup = group
    point.legendgrouptitle.text = group
    count = len(point.x)
    point.name = point.name.split(',')[1].strip() + f' (n = {count})'

fig.update_layout(legend_groupclick="toggleitem")

# Define visibility arrays for the interactive buttons
show_all = [True] * len(fig.data)
hide_all = ['legendonly'] * len(fig.data)
midgut_only = [True if trace.legendgroup == 'Midgut' else 'legendonly' for trace in fig.data]
hindgut_only = [True if trace.legendgroup == 'Hindgut' else 'legendonly' for trace in fig.data]

# Add custom interactive buttons
fig.update_layout(
    title_pad_l=300,
    updatemenus=[
        dict(
            type='buttons',
            direction='left',
            xanchor='left',
            x=1.0, 
            y=1.16,
            showactive=False,
            buttons=[
                dict(label='Show All', method='restyle', args=['visible', show_all]),
                dict(label='Hide All', method='restyle', args=['visible', hide_all]),
            ]
        ),
        dict(
            type='buttons',
            direction='left',
            xanchor='left',
            x=1.0, 
            y=1.1,
            showactive=False,
            buttons=[
                dict(label='Midgut Only', method='restyle', args=['visible', midgut_only]),
                dict(label='Hindgut Only', method='restyle', args=['visible', hindgut_only]),
            ]
        )
    ]
)

# Show and save the interactive plot
fig.show()
fig.write_html('pca_gut_cat_interactive.html')